# Generated by Django 4.0.6 on 2022-08-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_p_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='p_type',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Office', 'Office'), ('House', 'House'), ('Villa', 'Villa'), ('Others', 'Others')], default='Office', max_length=100, null=True),
        ),
    ]
