# Generated by Django 4.0.6 on 2022-08-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_p_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='zipcode',
            new_name='postal_code',
        ),
        migrations.AlterField(
            model_name='listing',
            name='p_type',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Office', 'Office'), ('House', 'House'), ('Villa', 'Villa'), ('Commercial', 'Commercial'), ('Others', 'Others')], default='Office', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
